---
- name: Install Docker, SonarQube, Trivy and Jenkins on Jenkins Server
  hosts: jenkins_host
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Add the current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Change permissions on docker socket
      file:
        path: /var/run/docker.sock
        mode: '0777'

    - name: Run SonarQube container
      docker_container:
        name: sonar
        image: sonarqube:lts-community
        state: started
        published_ports:
          - "9000:9000"
        restart_policy: always

    - name: Install dependencies for Trivy
      apt:
        name: ['wget', 'apt-transport-https', 'gnupg', 'lsb-release']
        state: present

    - name: Add the GPG key for the official Trivy repository
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
        state: present

    - name: Install Trivy
      apt:
        update_cache: yes
        name: trivy
        state: present

    - name: Install Java OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        update_cache: yes
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes
